image: python:3.7
before_script:
  - pip install pytest
stages:
  - test
  - package
  - deploy
pytest:
  stage: test
  script:
    - pytest ac_control_lambda/tests -vv
package:
  stage: package
  script:
    - ./bin/package_lambda.sh
  artifacts:
    paths:
      - ac_control_lambda.zip
deploy:
  stage: deploy
  script:
    - ./bin/deploy_lambda.sh
  dependencies:
    - package

